### ISSUE TITLE
Enable preview from editing layout

### ISSUE THREAD

**Issue by damaya** [netgen/NetgenAdminUIBundle#11]
Hi there, 

In legacy, users have the Preview available while editing a content before they publish, there is any setting to enable a preview in the edition view? or the only way is to extend that layout to include a preview link from the edition?

Thanks in advance.

**Comment by emodric** [comment]
Hi @damaya, thanks for reporting the issue!

I'm aware that the option to show the preview is missing from the edit mode, but this is currently a limitation of the admin UI design. Without going into specifics, as to why and how, we have this issue on our todo list since it was asked by couple of our clients too. I do not have any timeline, though.

**Comment by damaya** [comment]
Hi @emodric thanks for your answer, 

Kind regards!

**Comment by fg222cj** [comment]
@damaya 
I recently encountered this problem myself and did a workaround. I'm not sure if the issues page is an appropriate place to post the code, but feel free to email me if you want the details.

**Comment by damaya** [comment]
Hi there @fg222cj , thanks for the update, this sounds great, i think the best way is to make a pull request in this repository.
Thanks in advance!

**Comment by ilukac** [comment]
@fg222cj feel free to do a PR, @emodric loves reviewing and merging :)

**Comment by peterkeung** [comment]
@emodric Can you detail a bit more the reasons for the limitation? Mugo might be willing to put some time into this, because it's a deal breaker for us to use it for a particular client.

**Comment by emodric** [comment]
@peterkeung As far as I remember, the problem is that our form for showing the preview uses `GET`, while the original preview button from legacy admin was a part of content edit form flow (using `/content/edit` or `content/action`). This has the effect that you cannot return to the edit interface from the preview page once you use the new preview page.

**Comment by peterkeung** [comment]
Thanks. We'll see if we can get some time to look into this.

**Comment by thiagocamposviana** [comment]
Created a PR which might help here.

**Comment by emodric** [comment]
Implemented in #15, thanks to @thiagocamposviana !
